site_name: JDG рутина
plugins:
  - glightbox
theme:
  name: material

nav:
  - Головна: 'index.md'
  - Внесення різниці курсів: 'routine/exchange_rate_difference.md'
  - Віртальне бюро: 'routine/virtual_buro.md'
  - Податки JDG: 'routine/taxes.md'
  - Оплата ZUS: 'routine/zus.md'